name: Build Docker Image

on:
    push:
        branches: [ secret-deploy-test ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [default]
        include:
          - secrets: |
              FOO=I_AM_A_SECRET_LOOK_AT_ME
              BAR=ANOTHER_SECRET
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

    #   - name: Create foo secret
    #     run: echo "I_AM_A_SECRET_LOOK_AT_ME" > foo.txt

      - name: Build minimal image with secret
        uses: docker/build-push-action@v5
        with:
            context: .
            file: ./Dockerfile
            push: false
            secrets: ${{ matrix.secrets }}